# Generated by Django 5.0.6 on 2024-10-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenuitem',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Snakes', 'Snakes'), ('Beverages', 'Beverages'), ('Diet Food', 'Diet Food')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
