# Generated by Django 5.0.6 on 2024-10-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_foodmenuitem_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenuitem',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Snakes', 'Snakes'), ('Beverages', 'Beverages'), ('Diet_Food', 'Diet_Food')], max_length=25),
        ),
    ]
