# Generated by Django 5.0.6 on 2024-10-29 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_foodmenuitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('total_amount', models.FloatField()),
                ('discount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(default='pending', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrederItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Home.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='Home.foodmenuitem')),
            ],
        ),
    ]
