# Generated by Django 5.0.6 on 2024-10-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_order_discount_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenuitem',
            name='discount_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='rate',
            field=models.FloatField(),
        ),
    ]
