# Generated by Django 5.0.6 on 2024-10-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_deliveryaddress_ordered_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='estimated_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
