# Generated by Django 5.0.6 on 2024-10-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_deliveryaddress_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
