# Generated by Django 5.0.6 on 2024-10-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_deliveryaddress_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
