# Generated by Django 5.0.6 on 2024-10-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_deliveryaddress_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
